import './globals.css'

import { GoogleTags } from '../components/GoogleTags'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GoogleTags />
        {children}
      </body>
    </html>
  )
}